USE [master]
GO

/****** Object:  Database [TraceEvent]    Script Date: 25/01/2020 12:28:29 ******/
CREATE DATABASE [TraceEvent]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TraceEvent', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TraceEvent.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TraceEvent_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TraceEvent_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TraceEvent] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TraceEvent].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TraceEvent] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TraceEvent] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TraceEvent] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TraceEvent] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TraceEvent] SET ARITHABORT OFF 
GO

ALTER DATABASE [TraceEvent] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TraceEvent] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TraceEvent] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TraceEvent] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TraceEvent] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TraceEvent] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TraceEvent] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TraceEvent] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TraceEvent] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TraceEvent] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TraceEvent] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TraceEvent] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TraceEvent] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TraceEvent] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TraceEvent] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TraceEvent] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TraceEvent] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TraceEvent] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TraceEvent] SET  MULTI_USER 
GO

ALTER DATABASE [TraceEvent] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TraceEvent] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TraceEvent] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TraceEvent] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TraceEvent] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TraceEvent] SET QUERY_STORE = OFF
GO

USE [TraceEvent]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TraceEvent] SET  READ_WRITE 
GO

